// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySyv-JHAn7peRg2m-mGeZ_SGZOC6PoHY',
    appId: '1:427279140188:web:1ff4903db3c609559fad99',
    messagingSenderId: '427279140188',
    projectId: 'whatsonup-analytics',
    authDomain: 'whatsonup-analytics.firebaseapp.com',
    storageBucket: 'whatsonup-analytics.appspot.com',
    measurementId: 'G-PCES296HLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdhMxafI194WhXVd_SGMVKFoV1-mH0hw',
    appId: '1:427279140188:android:603a6f038b2f6d9e9fad99',
    messagingSenderId: '427279140188',
    projectId: 'whatsonup-analytics',
    storageBucket: 'whatsonup-analytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3dT18BV8uuayvQvUAiBZjcJHu4grIPg',
    appId: '1:427279140188:ios:bca4d1a5386b8ac09fad99',
    messagingSenderId: '427279140188',
    projectId: 'whatsonup-analytics',
    storageBucket: 'whatsonup-analytics.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3dT18BV8uuayvQvUAiBZjcJHu4grIPg',
    appId: '1:427279140188:ios:bca4d1a5386b8ac09fad99',
    messagingSenderId: '427279140188',
    projectId: 'whatsonup-analytics',
    storageBucket: 'whatsonup-analytics.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAySyv-JHAn7peRg2m-mGeZ_SGZOC6PoHY',
    appId: '1:427279140188:web:24de2aca4ec348df9fad99',
    messagingSenderId: '427279140188',
    projectId: 'whatsonup-analytics',
    authDomain: 'whatsonup-analytics.firebaseapp.com',
    storageBucket: 'whatsonup-analytics.appspot.com',
    measurementId: 'G-SLZSJ3X07Q',
  );
}
