
FROM node:16

WORKDIR /home/ubuntu


RUN mkdir -p /home/ubuntu/backend /home/ubuntu/storage-service /home/ubuntu/notification-service /home/ubuntu/gateway


RUN apt-get update && apt-get install -y curl

COPY Backend /home/ubuntu/backend
COPY storage-service /home/ubuntu/storage-service
COPY notification-service /home/ubuntu/notification-service
COPY gateway /home/ubuntu/gateway

WORKDIR /home/ubuntu/backend
RUN chmod +x ./gradlew
RUN sed -i 's/\r//' gradlew
RUN ./gradlew assemble

WORKDIR /home/ubuntu/storage-service
RUN npm install

WORKDIR /home/ubuntu/notification-service
RUN npm install

WORKDIR /home/ubuntu/gateway
RUN chmod +x ./gradlew
RUN sed -i 's/\r//' gradlew
RUN ./gradlew assemble

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082
EXPOSE 8083
EXPOSE 8084
EXPOSE 8085

WORKDIR /home/ubuntu
COPY start-services.sh ./start-services.sh
RUN chmod +x ./start-services.sh

CMD ["./start-services.sh"]
