name: Docker Image CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
    
      # Authenticate with Docker Hub
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u devforce123 --password-stdin

      # Build the Docker image
      - name: Build and Test Docker image
        run: docker build -t devforce123/backend:2.0 -f src/Backend/Dockerfile src/Backend/

  push:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
    
      # Authenticate with Docker Hub
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u devforce123 --password-stdin

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push devforce123/backend:2.0
