name: Backend Deployment Pipeline

on:
  push:
    branches:
      - feat/linter
    paths:
      - 'src/Backend/**' # Only run for changes in the Backend directory
      - 'scripts/deploy-api.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Backend/**' # Only run for changes in the Backend directory
      - 'scripts/deploy-api.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      SPRINGBOOT_ENV: ${{ secrets.SPRINGBOOT_ENV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set Google Cloud Project
        run: gcloud config set project ${{ env.GCP_PROJECT_ID }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Docker Auth
        run: |
          gcloud auth configure-docker "us-east1-docker.pkg.dev"

      - name: Create and write environment variables to .env files
        run: |
          echo "${{ env.SPRINGBOOT_ENV }}" > src/Backend/.env

      - name: Run deployment script
        run: |
          cd scripts
          if [ -f "deploy-api.sh" ]; then
            chmod +x deploy-api.sh
            ./deploy-api.sh
          else
            echo "deploy-api.sh script not found!"
            exit 1
          fi

      - name: Delete the .env files
        run: |
          rm -f src/Backend/.env
