name: CI with Gradle

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DB_URL: ${{ secrets.DB_URL }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                
            - name: Grant execute permission for gradlew
              run: chmod +x ./src/Backend/gradlew

            - name: Assemble with Gradle
              run: ./gradlew assemble
              working-directory: ./src/Backend

            - name: Run tests with Gradle
              run:  ./gradlew clean test codeCoverageReport 
              working-directory: ./src/Backend

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Log into Docker Hub
              run: echo $DOCKER_PASSWORD | docker login -u devforce123 --password-stdin

            - name: Build Docker image
              working-directory: ./src/Backend
              run: docker build -t decforce123/backend:3.0 .
      
            - name: Push Docker image to Docker Hub
              working-directory: ./src/Backend
              run: docker push devforce123/backend


