name: Springboot CI with Gradle

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DB_URL: ${{ secrets.DB_URL }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                
            - name: Grant execute permission for gradlew
              run: chmod +x ./src/Backend/gradlew

            - name: Assemble with Gradle
              run: ./gradlew assemble
              working-directory: ./src/Backend

            - name: Run tests with Gradle
              run: ./gradlew test
              working-directory: ./src/Backend

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

